apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-conf
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
{{- .Values.gateway.nginxConf | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
data:
  index.html: |
{{- .Values.gateway.indexHtml | nindent 4 }}
